#!/usr/bin/env bash
# Isolated contract test for scripts/install-standards.sh.
set -euo pipefail

REPOSITORY_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALLER="$REPOSITORY_ROOT/scripts/install-standards.sh"
TEMP_ROOT=$(mktemp -d /private/tmp/skills-sdlc-install-standards.XXXXXX)
trap 'rm -rf "$TEMP_ROOT"' EXIT

fail() {
  echo "install-standards test: $*" >&2
  exit 1
}

assert_file_content() {
  [ "$(<"$1")" = "$2" ] || fail "unexpected content in $1"
}

assert_absent() {
  [ ! -e "$1" ] && [ ! -L "$1" ] || fail "expected $1 to be absent"
}

assert_output() {
  rg -Fq -- "$2" "$1" || fail "expected output ($1) to contain: $2"
}

assert_not_output() {
  rg -Fq -- "$2" "$1" && fail "expected output ($1) to NOT contain: $2"
  return 0
}

assert_failure() {
  if "$@" >"$TEMP_ROOT/output" 2>&1; then
    fail "expected command to fail: $*"
  fi
}

STANDARDS_SOURCE="$TEMP_ROOT/nested standards"
mkdir -p "$STANDARDS_SOURCE"
printf 'Bash body\n' >"$STANDARDS_SOURCE/bash.md"
printf 'Coding body\n' >"$STANDARDS_SOURCE/coding.md"
printf 'Go body\n\n\n' >"$STANDARDS_SOURCE/go.md" # trailing blank lines to be trimmed

# --help mentions every option
"$INSTALLER" --help >"$TEMP_ROOT/help"
for option in --output-dir --force --list --standards-dir -h --help; do
  assert_output "$TEMP_ROOT/help" "$option"
done

# --list prints available names
"$INSTALLER" --standards-dir "$STANDARDS_SOURCE" --list >"$TEMP_ROOT/list"
for name in bash coding go; do
  assert_output "$TEMP_ROOT/list" "$name"
done

# Positional compile: order honoured, .md suffix optional, header names sources
"$INSTALLER" --standards-dir "$STANDARDS_SOURCE" coding go bash \
  >"$TEMP_ROOT/compiled-order"
assert_output "$TEMP_ROOT/compiled-order" \
  'Generated by scripts/install-standards.sh from skills-sdlc standards/: coding.md go.md bash.md'
assert_output "$TEMP_ROOT/compiled-order" \
  'Regenerate: ./scripts/install-standards.sh coding go bash'
# bodies appear in the order given
coding_pos=$(rg -n -F 'Coding body' "$TEMP_ROOT/compiled-order" | cut -d: -f1)
go_pos=$(rg -n -F 'Go body' "$TEMP_ROOT/compiled-order" | cut -d: -f1)
bash_pos=$(rg -n -F 'Bash body' "$TEMP_ROOT/compiled-order" | cut -d: -f1)
[ "$coding_pos" -lt "$go_pos" ] || fail 'coding should precede go'
[ "$go_pos" -lt "$bash_pos" ] || fail 'go should precede bash'
# trailing blank lines from go.md were trimmed: exactly one blank line, then Bash body
awk '/^Go body$/{getline; if ($0 != "") { print "not trimmed: " $0; exit 1 }}' \
  "$TEMP_ROOT/compiled-order" || fail 'trailing blank lines were not trimmed'

"$INSTALLER" --standards-dir "$STANDARDS_SOURCE" coding.md go.md >"$TEMP_ROOT/suffix-form"
assert_output "$TEMP_ROOT/suffix-form" 'Coding body'

# Unknown name fails, nothing written, available standards listed
assert_failure "$INSTALLER" --standards-dir "$STANDARDS_SOURCE" nonexistent
assert_output "$TEMP_ROOT/output" 'unknown standard: nonexistent'
assert_output "$TEMP_ROOT/output" 'coding'

# Duplicate name fails
assert_failure "$INSTALLER" --standards-dir "$STANDARDS_SOURCE" coding coding
assert_output "$TEMP_ROOT/output" 'duplicate standard: coding'

# Missing standards dir fails
assert_failure "$INSTALLER" --standards-dir "$TEMP_ROOT/missing-standards" coding
assert_output "$TEMP_ROOT/output" 'standards directory does not exist'

# Empty standards dir fails
EMPTY_STANDARDS="$TEMP_ROOT/empty standards"
mkdir -p "$EMPTY_STANDARDS"
assert_failure "$INSTALLER" --standards-dir "$EMPTY_STANDARDS" coding
assert_output "$TEMP_ROOT/output" 'no standards .md files found'

# Interactive: selection on stdin compiles in typed order; prompt on stderr only
printf 'go bash\n' | "$INSTALLER" --standards-dir "$STANDARDS_SOURCE" \
  >"$TEMP_ROOT/interactive-out" 2>"$TEMP_ROOT/interactive-err"
assert_output "$TEMP_ROOT/interactive-err" 'Select standards in compile order'
assert_not_output "$TEMP_ROOT/interactive-out" 'Select standards in compile order'
go_pos=$(rg -n -F 'Go body' "$TEMP_ROOT/interactive-out" | cut -d: -f1)
bash_pos=$(rg -n -F 'Bash body' "$TEMP_ROOT/interactive-out" | cut -d: -f1)
[ "$go_pos" -lt "$bash_pos" ] || fail 'interactive order not honoured'

# Interactive: numeric selection also works
printf '2 1\n' | "$INSTALLER" --standards-dir "$STANDARDS_SOURCE" \
  >"$TEMP_ROOT/interactive-numeric"
assert_output "$TEMP_ROOT/interactive-numeric" \
  'from skills-sdlc standards/: coding.md bash.md'

# Interactive: empty input fails
assert_failure bash -c "printf '\n' | '$INSTALLER' --standards-dir '$STANDARDS_SOURCE'"
assert_output "$TEMP_ROOT/output" 'no standards selected'

# --output-dir: writes the file
OUTPUT_DIR="$TEMP_ROOT/output dir"
mkdir -p "$OUTPUT_DIR"
"$INSTALLER" --standards-dir "$STANDARDS_SOURCE" --output-dir "$OUTPUT_DIR" coding go \
  >"$TEMP_ROOT/write-stdout"
[ -f "$OUTPUT_DIR/CODING_STANDARDS.md" ] || fail 'expected CODING_STANDARDS.md to be written'
assert_output "$OUTPUT_DIR/CODING_STANDARDS.md" 'Coding body'
first_contents="$(<"$OUTPUT_DIR/CODING_STANDARDS.md")"

# rerun with same selection: unchanged, no backup created
"$INSTALLER" --standards-dir "$STANDARDS_SOURCE" --output-dir "$OUTPUT_DIR" coding go \
  >"$TEMP_ROOT/rerun-same-out" 2>"$TEMP_ROOT/rerun-same-err"
assert_output "$TEMP_ROOT/rerun-same-err" 'already up to date'
assert_file_content "$OUTPUT_DIR/CODING_STANDARDS.md" "$first_contents"
if compgen -G "$OUTPUT_DIR/CODING_STANDARDS.md.backup.*" >/dev/null; then
  fail 'unchanged rerun created a backup'
fi

# rerun with different selection, no --force: refuses, leaves original intact
assert_failure "$INSTALLER" --standards-dir "$STANDARDS_SOURCE" --output-dir "$OUTPUT_DIR" bash
assert_output "$TEMP_ROOT/output" 'refusing to replace existing file'
assert_file_content "$OUTPUT_DIR/CODING_STANDARDS.md" "$first_contents"
if compgen -G "$OUTPUT_DIR/CODING_STANDARDS.md.backup.*" >/dev/null; then
  fail 'refused write created a backup'
fi

# rerun with different selection, --force: writes new content, one backup with old content
"$INSTALLER" --standards-dir "$STANDARDS_SOURCE" --output-dir "$OUTPUT_DIR" --force bash \
  >/dev/null
assert_output "$OUTPUT_DIR/CODING_STANDARDS.md" 'Bash body'
mapfile -t backups < <(compgen -G "$OUTPUT_DIR/CODING_STANDARDS.md.backup.*")
[ "${#backups[@]}" -eq 1 ] || fail 'expected exactly one backup'
assert_file_content "${backups[0]}" "$first_contents"

# --output-dir with a missing directory fails
assert_failure "$INSTALLER" --standards-dir "$STANDARDS_SOURCE" \
  --output-dir "$TEMP_ROOT/does not exist" coding
assert_output "$TEMP_ROOT/output" 'output directory does not exist'

# Unknown option and missing-argument options report install-standards: prefix
assert_failure "$INSTALLER" --unknown
assert_output "$TEMP_ROOT/output" 'install-standards: unknown option: --unknown'
for option in --output-dir --standards-dir; do
  assert_failure "$INSTALLER" "$option"
  assert_output "$TEMP_ROOT/output" "install-standards: $option requires a directory"
done

echo 'install-standards contract test passed'
