#!/usr/bin/env bash
# Compile chosen standards/*.md documents, in the given order, into CODING_STANDARDS.md.
set -euo pipefail

REPOSITORY_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STANDARDS_DIR="$REPOSITORY_ROOT/standards"
OUTPUT_DIR=""
FORCE=false
LIST=false

usage() {
  cat <<'EOF'
Usage: ./scripts/install-standards.sh [options] [standard...]

Compile the named standards documents, in the order given, to stdout.

With no standard arguments, prompts interactively (selection on stderr,
compiled output on stdout).

Options:
  --output-dir DIR      Write DIR/CODING_STANDARDS.md instead of stdout.
  --force               Back up a conflicting CODING_STANDARDS.md, then write.
  --list                List available standards and exit.
  --standards-dir DIR   Override standards/.
  -h, --help            Print this help text.
EOF
}

die() {
  echo "install-standards: $*" >&2
  exit 1
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --output-dir)
      [ "$#" -ge 2 ] || die '--output-dir requires a directory'
      OUTPUT_DIR="$2"
      shift
      ;;
    --force) FORCE=true ;;
    --list) LIST=true ;;
    --standards-dir)
      [ "$#" -ge 2 ] || die '--standards-dir requires a directory'
      STANDARDS_DIR="$2"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    --) shift; break ;;
    -*) die "unknown option: $1" ;;
    *) break ;;
  esac
  shift
done

[ -d "$STANDARDS_DIR" ] || die "standards directory does not exist: $STANDARDS_DIR"
STANDARDS_DIR="$(cd "$STANDARDS_DIR" && pwd -P)"

declare -a available_names=()
declare -A available_paths=()
discover_standards() {
  local candidate name
  shopt -s nullglob
  for candidate in "$STANDARDS_DIR"/*.md; do
    [ -f "$candidate" ] || continue
    name="$(basename "$candidate" .md)"
    available_names+=("$name")
    available_paths["$name"]="$candidate"
  done
  shopt -u nullglob
  [ "${#available_names[@]}" -gt 0 ] || die "no standards .md files found in: $STANDARDS_DIR"
}
discover_standards

print_available() {
  local name
  for name in "${available_names[@]}"; do
    printf '  %s\n' "$name"
  done
}

if "$LIST"; then
  print_available
  exit 0
fi

# Resolve a user-supplied token (name or name.md) to a canonical standard name.
resolve_name() {
  local token="$1" candidate="$1"
  candidate="${candidate%.md}"
  if [ -n "${available_paths[$candidate]+x}" ]; then
    printf '%s\n' "$candidate"
    return 0
  fi
  echo "install-standards: unknown standard: $token" >&2
  echo "Available standards:" >&2
  print_available >&2
  return 1
}

declare -a selection=()

add_selection() {
  local token="$1" name
  name="$(resolve_name "$token")" || exit 1
  local existing
  for existing in "${selection[@]}"; do
    [ "$existing" = "$name" ] && die "duplicate standard: $name"
  done
  selection+=("$name")
}

if [ "$#" -gt 0 ]; then
  for token in "$@"; do
    add_selection "$token"
  done
else
  echo "Available standards:" >&2
  list_index=1
  for name in "${available_names[@]}"; do
    printf '  %d) %s\n' "$list_index" "$name" >&2
    list_index=$((list_index + 1))
  done
  printf '\n' >&2
  printf 'Select standards in compile order (numbers or names, space separated): ' >&2
  IFS= read -r reply || die "no standards selected"
  [ -n "${reply//[[:space:]]/}" ] || die "no standards selected"
  read -ra tokens <<<"$reply"
  for token in "${tokens[@]}"; do
    if [[ "$token" =~ ^[0-9]+$ ]]; then
      idx=$((token - 1))
      [ "$idx" -ge 0 ] && [ "$idx" -lt "${#available_names[@]}" ] \
        || die "unknown standard number: $token"
      add_selection "${available_names[$idx]}"
    else
      add_selection "$token"
    fi
  done
fi

[ "${#selection[@]}" -gt 0 ] || die "no standards selected"

render() {
  local name file_list=""
  for name in "${selection[@]}"; do
    file_list="$file_list $name.md"
  done
  file_list="${file_list# }"

  printf '<!-- Generated by scripts/install-standards.sh from skills-sdlc standards/: %s\n' "$file_list"
  printf '     Regenerate: ./scripts/install-standards.sh %s -->\n' "${selection[*]}"

  # $(...) strips trailing newlines, so this trims each document's trailing
  # blank lines and re-adds exactly one, joining documents with one blank line.
  for name in "${selection[@]}"; do
    printf '\n%s\n' "$(cat "${available_paths[$name]}")"
  done
}

if [ -n "$OUTPUT_DIR" ]; then
  [ -d "$OUTPUT_DIR" ] || die "output directory does not exist: $OUTPUT_DIR"
  target="$OUTPUT_DIR/CODING_STANDARDS.md"
  tmp_file="$(mktemp "$OUTPUT_DIR/.CODING_STANDARDS.md.XXXXXX")"
  trap 'rm -f "$tmp_file"' EXIT
  render >"$tmp_file"

  if [ -e "$target" ]; then
    if diff -q "$tmp_file" "$target" >/dev/null 2>&1; then
      rm -f "$tmp_file"
      trap - EXIT
      echo "install-standards: $target is already up to date" >&2
      exit 0
    fi
    "$FORCE" || die "refusing to replace existing file: $target (rerun with --force)"
    backup="$target.backup.$(date +%Y%m%d%H%M%S)"
    suffix=1
    while [ -e "$backup" ]; do
      backup="$target.backup.$(date +%Y%m%d%H%M%S).$suffix"
      suffix=$((suffix + 1))
    done
    mv "$target" "$backup"
    echo "install-standards: backed up $target to $backup" >&2
  fi
  mv "$tmp_file" "$target"
  trap - EXIT
  echo "install-standards: wrote $target" >&2
else
  render
fi
